version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: agendamento-spring

    environment:
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: springpassword
      POSTGRES_DB: agendamento_db
    ports:
      - "5454:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: